In [40]:
import torch
import torch.nn as nn
from torch.nn import functional as F
from IPython.display import Image, display

# device stuff goes here

block_size = 64      # Sequence length
batch_size = 128     # Amount of batchs
max_iters = 100     # How many interations

learning_rate = 3e-4 # updating model weights by loss funcition
# 3e-3, 3e-4, 1e-3, 1e-4
eval_iters = 150     # loss function report

n_embd = 384         # Number of total dims we want to capture from all the heads concats too big
n_head = 8           # Heads runing in pararlel
n_layer = 8          # Amount of decoder blocks
dropout = 0.2        # 20% of the total neurons will be 'shut down'


# embedding_vector = []

In [32]:
chars = ''
with open('wizard_of_oz.txt', 'r', encoding='utf-8') as f:
    text = f.read()
    chars = sorted(set(text))
    
vocab_size = len(chars)

In [ ]:
# os
# tqdm - Progress Bar
def xz_files_in_dir(directory):
    files = []
    for filename in os.listdir(directory):
        if filename.endswith('.xz') and os,path.isfile(os.path.join(directory, filename))
            files.append(filename)
    
    return files
    
folder_path = 
output_path = 
vocab_file = 
split_files = 


In [3]:
string_to_int = { ch:i for i, ch in enumerate(chars) }
int_to_string = { i:ch for i, ch in enumerate(chars) }

encode = lambda s: [ string_to_int[c] for c in s ]
decode = lambda l: ''.join([int_to_string[i] for i in l ])

data = torch.tensor(encode(text), dtype=torch.long)

In [4]:
n = int(0.9*len(data))
train_data = data[:n]
test_data = data[n:]

def get_batch(split):
    data = train_data if split == 'train' else test_data
    ix = torch.randint(len(data) - block_size, (batch_size,))
    print(ix)
    x = torch.stack([ data[i:i+block_size] for i in ix ])
    y = torch.stack([ data[i+1:i+block_size+1] for i in ix])
    return x, y

In [36]:
class Head(nn.Module):
    ''' One head of self-attention '''
    
    def __init__(self, head_size):
        super().__init__()
        self.key = nn.Linear(n_embd, head_size, bias=False)
        self.query = nn.Linear(n_embd, head_size, bias=False)
        self.value = nn.Linear(n_embd, head_size, bias=False)
        # Register model state to prevent over head computation extensivily
        self.register_buffer('tril', torch.tril(torch.ones(block_size, block_size)))
        self.dropout = nn.Dropout(dropout)
        
    def forward(self, x):
        # input of size ( batch, time-step, chanels)
        # output of size ( batch, time-step, head size)
        B, T, C = x.shape
        k = self.key(x)
        q = self.query(x)
        
        # Scaling dot product atention
        wei = q @ k.transpose(-2, -1) * k.shape[-1]**-0.5 
        wei = wei.masked_fill(self.tril[:T, :T] == 0, float('-inf'))
        # Sharp values to make some of then to stand out 
        wei = F.softmax(wei, dim=-1)
        wei = self.dropout(wei)
        #weight agregation of the values
        v = self.value(x)
        out = wei @ v 
        return out
        
        
        
class MultiHeadAttention(nn.Module):
    ''' Multiple heads of self-attention in parallel '''
    
    def __init__(self, num_heads, head_size):
        super().__init__()
        self.heads = nn.ModuleList([Head(head_size) for _ in range(num_heads)])
        self.proj = nn.Linear(head_size * num_heads, n_embd) # Hs * Nh = n_embd
        self.dropout = nn.Dropout(dropout) # 
        
    def forward(self, x):
        out = torch.cat( [h(x) for h in self.heads], dim=-1 ) # (Batch, T, F) f = feature dimenson
        # (B, T, [h1, h1, h1, h1, h2, h2, h2, h2, h3 ...]) 4 features by head, concatenate each feature sequentialy
        out = self.dropout(self.proj(out))
        return out

class FeedFoward(nn.Module):
    """ a simple linear layer followed by a non-linearity """

    def __init__(self, n_embd):
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(n_embd, 4 * n_embd),
            nn.ReLU(),
            nn.Linear(4 * n_embd, n_embd),
            nn.Dropout(dropout),
        )

    
    def forward(self, x):
        return self.net(x)

class Block(nn.Module):
    ''' Transformer block: communication followed by computation '''
    
    def __init__(self, n_embd, n_head):
        super().__init__()
        head_size = n_embd // n_head  # How many features the heads are capturing
        self.sa = MultiHeadAttention(n_head, head_size) # self attention
        self.ffwd = FeedFoward(n_embd)
        self.ln1 = nn.LayerNorm(n_embd) 
        self.ln2 = nn.LayerNorm(n_embd)
        
    def forward(self, x):
        y = self.sa(x)
        x = self.ln1(x + y)
        y = self.ffwd(x)
        x = self.ln2(x + y)
        
        return x
        
class GPTLanguageModel(nn.Module):
    ''' GPT like model '''
    def __init__(self, vocab_size):
        super().__init__()
        self.token_embedding_table = nn.Embedding(vocab_size, n_embd) # 80x80 matrix, with probabilities to all words in corpus
        # Learnable Embeddings
        self.position_embedding_table = nn.Embedding(block_size, n_embd)
        # Decoder Layers generation
        self.blocks = nn.Sequential(*[Block(n_embd, n_head=n_head) for _ in range(n_layer)])
        
        #End of the arquiteture, help model conversion
        self.ln_f = nn.LayerNorm(n_embd)
        # Language modeling head 
        self.lm_head = nn.Linear(n_embd, vocab_size)
        
        self.apply(self._init_weights)
        
    def _init_weights(self, module):
        if isinstance(module, nn.Linear):
            torch.nn.init.normal_(module.weight, mean=0.0, std=0.02) # dropout
            if module.bias is not None:
                torch.nn.init.zeros_(module.bias)
        elif isinstance(module, nn.Embedding):
            torch.nn.init.normal_(module.weight, mean=0.0, std=0.02)
        
        
    def forward(self, index, targets=None):
        B, T = index.shape # B, T + 1  ...
        
        
        # idx and targets are both (B,T) tensor of integers
        tok_emb = self.token_embedding_table(index) # (B,T,C)
        pos_emb = self.position_embedding_table(torch.arange(T)) # (T,C)
        x = tok_emb + pos_emb # (B,T,C)
        x = self.blocks(x) # (B,T,C)
        x = self.ln_f(x) # (B,T,C)
        logits = self.lm_head(x) # (B,T,vocab_size)
        
        if targets is None:
            loss = None
        else:
            B, T, C = logits.shape
            logits = logits.view(B*T, C)
            targets = targets.view(B*T)
            loss = F.cross_entropy(logits, targets)
        
        return logits, loss
    
    def generate(self, index, max_new_tokens):
        # Index is (B, T) array of indices in the current context
        for _ in range(max_new_tokens):
            # Gen the predictions
            logits, loss = self.forward(index)
            # Foucus only on the last time step
            logits = logits[:, -1, :] # B, C
            probs = F.softmax(logits, dim=-1) # B, C
            # Sample of the distribution
            index_next = torch.multinomial(probs, num_samples=1) # B, 1
            # Append the index to the running sequence
            index = torch.cat(( index, index_next ), dim=1 ) # (B, T+1)
        
        return index
    
    
model = GPTLanguageModel(vocab_size)
# m = model.to(device)

#context = torch.zeros((1, 1), dtype=torch.long ) # device=device for cuda operations torch.long = 6 bits, float
#generated_chars = decode(model.generate( context, max_new_tokens=500 )[0].tolist() )
#print(generated_chars)

In [ ]:
# The architeture we had implemented
image = 'assets/dec_arch_1.png'
display(Image(image))

In [38]:
@torch.no_grad()
def estimate_loss():
    out = {}
    model.eval()
    
    for split in ['train', 'val']:
        losses = torch.zeros(eval_iters)
        
        for k in range(eval_iters):
            X, Y = get_batch(split)
            logits, loss = model(X, Y)
            losses[k] = loss.item()
            
        out[split] = losses.mean()
        
    model.train()
    return out

In [41]:
optimizer = torch.optim.AdamW(model.parameters(), lr=learning_rate)
# Training Loop + optimizer
for iter in range(max_iters):
    
    if iter % eval_iters == 0: 
        losses = estimate_loss()
        print(f"step: {iter}, Train loss{losses['train']:.3f}, Val Loss: {losses['val']:.3f} ")
    
    # Some sample batch data
    xb, yb = get_batch('train')
    
    logits, loss = model.forward(xb, yb)
    optimizer.zero_grad(set_to_none=True) # Previous gradient dosent affect the new seen data
    loss.backward()
    optimizer.step()

    print(loss.item()) # 3.0913524627685547

tensor([141270,  80932, 178892, 150474,   5697, 109804, 126128, 118107,    131,
          1190,   7876, 176558, 157836,  67173, 102873,  33927, 101288,  58856,
        175813, 145844,  28733,  84593, 113974, 185142, 122397, 133097,   5939,
         90477,  81161,  56951,   3682,  58259,  26052,  18457,  81712,  49822,
        127975, 164503,  19813,  72653, 108365,  67201,  81539, 113853,  26881,
          3345, 114673, 138388,  23553,  24478,  77120,  52379, 154809, 127226,
        128595, 113558, 149001, 122918,  31683,  74960, 114547,   5784,  61923,
         93948,  71043,  69160, 110995, 135240, 130428,  38824, 154524, 159570,
         65206, 176292, 166556,  82853, 102371,  99133, 185552,  81396, 100418,
        174223,  11826, 141537, 115867,  35386,  29907, 144138, 119433,  50454,
         51144, 105877, 114058,  79359,    698,  81249,  41817, 112201,  96244,
        183619,  27922, 145676, 104835,  33977,  95848, 132160,  36382,  20925,
        136933,  53609,  94593, 185028, 

tensor([  6795,  43065,  91677,  94642,  72650, 150202,  16216, 163051, 107109,
         46783, 152784, 163974, 122476, 180548,  49723, 108503, 163263,  53390,
         47915, 116781, 176725,  80470, 119636, 142257,  50463,   7109, 147200,
         81550, 182702,  64457, 173383, 151498, 139083,  63640,  61950,  10870,
        158472,   7140,  75262,  33849, 119283,  57596, 157307, 133541,  24247,
        145444,  26776,  99319,   9196, 139789, 133511, 104804,  24419, 176536,
        185676,  89877, 101275,  77849, 155054,  69967, 171209, 122780, 139929,
        149115,  86035,   9136, 185525, 126668,  11085, 124138,  67631,  85458,
          3155,  87059, 171543, 100698, 138107,  74549, 180769,  62108, 147227,
        181104, 153551, 154206, 117920, 126646, 179454,  82784, 182122, 185725,
         76526, 111399,  29251,  14140, 141244, 100401,  83267, 139615,  68440,
         82753,   7747, 137397, 123814,  41019, 102774,  97087, 166094, 174963,
         76492, 166664, 139123,  33973, 

tensor([169003, 163980,  52788, 173035, 172914, 121030,  88151, 180517,  41022,
        148113,  35532, 118760,   1820, 161221,  28645,  30548,  48151, 139612,
        110249, 180320,  17770,  37602, 166084,  30443,  46123, 154462,  55995,
         37411,  72628, 118086,    286,   1570,  50822, 125939,  68332, 117991,
        135159,  40307, 101704,  22798, 181199,  83113,  89194, 125410,  41735,
        108850, 148774,  64613,  85110, 128571, 159662,  29487,  14377, 153711,
         33711,  71516, 143493, 178518, 111410,  24844, 185272,  57558, 170275,
        155422,  90578,  47643,  19770, 185489, 175291, 121345,  44448, 127436,
          7974, 163678,  52026, 138102,  47618, 121857, 106326,  63735,  40443,
        151130,  62606,  66999,  80658,  74790, 109780,  83298, 126222,  67536,
         11356, 152565, 128663,  71270,  67828,  23244,  80172,  62695,  53764,
         28078, 128207,  62666, 102569, 165309,  72826, 126068,  16936,  86935,
         37581, 183881, 157140,  51127, 

tensor([172424, 152930,  74943, 108577,  27073, 159486,  40302,  67382,  64436,
        176133, 184462,  44149,  79041,   4038,  60614,  73930,  87069,  42330,
        136211,   7354,  11366,  45846, 169269,  68290, 119441,  73779,  11596,
        158726, 104652, 114099,  60197,  41762,  13556,  49861,  51817,  42902,
        172453, 141289,  39089,  96656,  74702, 126816,  75923, 112728, 128286,
        173306, 111203,  52549, 118989,  57007, 100063, 124595,  91177, 137420,
         63820,  38673,   4690, 181319, 101696, 124550, 168901,  62289, 102440,
         21483, 146336,  33221,   9199,  79952,   5953, 171868, 133868, 129570,
        182808,  62150, 155292,  63660, 181283, 124228, 111408,  83270, 132145,
        125384, 113645, 141046, 176045,  11709, 164382,  72943,   2531,  84431,
        145803, 118630,  44367, 122318, 117451,  96302, 183787,  43338, 158718,
        109803, 122136, 124135, 147581, 108556,  95385,  38940,   3745,  42055,
         50667, 103508, 154262,  18463, 

tensor([179768,  81537, 110595,  18134, 115320,  22261,  86590,  98997,   2622,
        165429, 138140,    203, 133936,  28392, 139048, 167606,  39560, 152980,
         15093, 134227, 154302,  66187, 130503, 140690,  59607,  18120, 149656,
        112373, 178915, 117219,  63402, 136769, 107493,  71969, 102127, 136952,
          9966,  54002, 149807,  96480, 103821, 120852, 158834, 161259,  54571,
         85250, 125466,  20469,  92785, 171071,  14669,  74898, 169460,  30142,
         34554,   3685,   8137, 160393,  25944,  83088,  66435, 124599, 149651,
        173708, 107950,  45282,  84750, 132746,   1376, 112202, 106955, 121593,
          8152,  82046,  86756, 168936,  22031, 128048, 116932,  39683,  79649,
          2335,  74795, 102321, 179771,   7914, 167314, 171773,  31214,  72644,
         10094,  52801, 125911, 111323, 179715, 159689,  78099,  69901, 123348,
        129996,  98424,  98079, 159829,  78763,  14323,  17223, 115586,  30203,
         74927,  90875,  82887,  11806, 

tensor([110249,  56243,  73352,  27408,  25286, 157336, 183302,  58881,  16030,
        155576,  51598,   5631, 175374, 147240,  84091, 137300,  78026,  78178,
        111820, 174428, 157124, 139380, 164685, 100893, 116011, 136362, 162137,
        126546, 155276,  70368, 100043,  64206,  65711,  67868,  20788,  83295,
        170539, 151497, 137726, 170972, 175665,  17202,  33182,  29168,  79606,
         73158, 129493,  38900, 109044, 153784,  48957,  37672,  19568,  17354,
        125310,  88872, 172066,  23608, 149469,  76891, 120547, 100379,  79652,
        120048,  18875,  51524,   5694,  98400,  80679,  39362,  13003, 148592,
         98409, 168814,  10358,  24386,  33276, 120511,  45170,  66907, 108484,
        125902,   5687,  70780, 100538, 133368, 128789, 127540, 125853,  36816,
         36872,  85784, 143930, 142405, 169325,  51118,  64335,  67428, 124223,
         88494,  94521, 119999, 157976,  77706, 111039,  14361,  18579,  20039,
        164492, 168922, 142581, 114603, 

tensor([120765, 115152,  53268, 185680,  38533,   3047,  89422,  62700,  66637,
         57566,  80800,  47373,  39522, 179724,  67163, 171445,  99786,  69795,
        171081, 126909,  41601, 116021, 178424,  71930, 169707,  45465, 132931,
         79733,  31530,  79080, 162093,  87346,   9316,  93151,  83155,  76757,
        170594, 170830,  37223,  82005,  96134,  53504, 124817, 163006, 109539,
        174440,  60775, 119900,  52784, 165358, 138585,  46496, 128729, 132092,
         48713, 157157,  13452,  17743,  92621,  83966, 124867,  32521,  87560,
        172069, 151771,  61282, 140758, 136402, 164416,  77947, 183367,  59934,
         61514,  96410,  14537,  81573,  38221, 106578, 138016, 152157, 175044,
          3129, 146011,  25380,  27411, 118452, 128726,  31878, 150444,   8532,
        135073,  27661,  56677, 179490,  16882,   5304,  45956,  43453, 151958,
        147391, 130637, 182041,  62263, 176417, 111085, 160557,  61261, 163380,
         39499,  21699,  26965,  37497, 

tensor([131734, 165476,   2904,  15180, 129436,  21399, 111914, 125228, 155184,
         81237,  51403, 156021, 170148,   5219, 145911, 146689, 169798, 109655,
        103518,  82462,  86754, 113111,  28557,  61300,  29748,  69855,  22524,
          3257, 117988, 169439,  66755,  79913,  26360, 167789, 120811, 102983,
         83323, 125845,  70897, 171912,  75110,  29278,  72620,  82430, 124439,
        142434, 102899, 154567, 160264,  51143,  33997,  42512, 135393, 151779,
         12351, 142620,  31902,  39925,  30556, 153992,  78460,   5572, 130573,
         54248,  69654,  13622, 138326,  53337, 120731, 160438,  28037, 163156,
         55488, 155730,   1051, 146201,  94618,  89343,  77337, 144482, 136371,
         23644,  76671, 147979, 139643, 101473, 171044, 166011,  77545,  96183,
        105644, 154992, 129123,  57119,  50486, 160189,  87275, 116721,  16620,
        179349, 146685, 138519, 122913,  10210,  30620, 113081,  76075,  39486,
         87382,  55134,  45399, 143676, 

tensor([ 34780, 159081,  89373,  16490, 108804, 124281,  19957,  92119,  84441,
        144288, 135307, 100221,  44401, 107822, 104499,  73397,  15610,  46511,
        180210, 106126, 174635, 173080, 157312, 147008, 128394, 175324, 141382,
         86170,  40985,  41254,  38108, 111626, 183856,  64444, 158139,  16760,
         71224,  39386,   9481, 165979,  60850, 131130, 133862,  28502, 182616,
        113173,  97463, 143122,  11720,  59442,  96580,  51317, 185080,  69896,
        107964, 109589, 164154, 128645,  48778,  30674,  79826,  17457, 150104,
        127749,  86430, 151723,  18908,  68858, 107236,  13667,  20961,  17954,
        175734, 179001,  32942,  78797,  37286, 171635, 182631, 116262,  70785,
         74458,  88756,  26029, 135805, 144826,   6157,  62168,  85626,  75975,
        147619,  81334,  78977,  96165, 152065,  29161,   5009,   4858,  82573,
         38761, 176400,  12655,  91117,  52700, 170179,  61193,  77917,  26426,
        159620, 171550, 109874,   2421, 

tensor([177959, 118897, 138527, 145194, 109262,  92044, 123517, 161745,  63761,
        150978,  49921,  98991, 119894,  14044, 183287, 179271, 157678,  89524,
        107301,  57502, 167049, 178548, 139780,  38588,  38001, 171901,  91107,
        154471,  90066,  25360, 132099,  72933,  33580, 142537,   2212,  26603,
          6894, 185706,  43275, 112053, 173062, 139872, 185744,   8454, 168224,
        116606, 135341,  66694,  27795,  26172, 116517, 174965,   1797,  24794,
         40330,  61482,  43401, 100287,  43937, 165965,  29891,  79622, 162241,
         72827, 171478, 141235,  85681, 138727,  73777,  12206,  45328,  81270,
        141701, 153124, 103478, 124625, 158468,  86418, 121356,  36472,  76734,
         65335, 128088,  57749,  10617,  60213,  15605, 100315,  13416, 161589,
        166841, 142990, 139344, 151113,  42535, 155065, 109771, 109193,  29393,
        142722,  79734,  85875, 160369, 130346, 144357,  91632,  80229,  12584,
        182446,  78853, 121312,  75292, 

tensor([132489, 117362, 161716,  90740,  93454, 110184,  78395,  11032,  85230,
         27575,  18075,  86125,  38110,  46243, 109505, 153663, 167003,  23794,
        123215,  84818, 176402,  21546, 169133,  82532,  38407,  93061,   3516,
        141574,  35591,  15571,  45614,  67979,  42006, 120026, 137200, 100775,
         47954, 112781, 143548, 144279,  51865,  35450, 128477, 135327,  81544,
         96117,  59835,  77576,  48179,  10909,   5328,  11886,   1855,  72590,
        160701,  88815, 166356,  98273,  74611, 105344, 166090, 156018,   9912,
         33482, 157033,  97621,  73516,  91997,  94381,  33522, 138012, 136212,
        111949, 151952, 134677, 118981,  97037, 141978, 169063, 160385,  59180,
         34122, 184003, 104446,  35966,  13604,  89370,  22066, 176777,  76849,
        101943,  43309, 131991, 108891, 127960,  60449, 100499, 115624, 122509,
        160071, 131248,  77826,  63492,  36445, 131631,   9813,  10103,  54617,
        130385, 145018,  26664,  75000, 

tensor([ 44004, 159062,  18879, 135473, 103717,  52334,  53197, 115482,  10776,
         65907,  79978,  25427,  46551,  35724,  18888,  60301,  99434,   5556,
         73191, 164956, 144972,  71452,  60122, 159206, 139007,  34223,  48925,
         84959, 150513,  39597,  47811, 146807,  72173, 121580, 132356,  39518,
         47994,  64421, 120370,  69123,  83947,  86894,  96700, 151528, 107843,
         62475,  13412,  18572, 131557,  49342,  73109,  93300, 145479,  58324,
        160091,  49536,  21028,  18261,  29740, 108062,  42388, 153166,  70898,
         39457, 117404, 171495,  17356,  87443,  81636, 134842,  92087,  99055,
          8939,  91271,  85260, 122733, 138506, 122292,  66851,  19268,  22909,
         44786,  20925, 184770,  73351, 117563, 118003,  36087, 168067, 119680,
        144945,  10909,  31417, 118276, 116197, 101610, 127987,  12706,  26684,
        134921,  98719,  85204, 110311, 183620,  10945, 138763,  85131,  75808,
         91810, 134131, 171982,  61439, 

tensor([151528,   1609, 175714, 173577, 176484, 140249,  56728, 182312, 132497,
        135909, 129742,  46704, 173258,  13918, 165049, 179205,  49378, 127601,
         83614, 183574, 158654, 102706,  12819, 124929,  86371,  65590,  64632,
        116231, 155273, 137653, 137208,  27410,  35911,  19906,  55824, 113442,
        110405, 181294,  81822,  36273, 164336, 154389,  82804,  25488,  85019,
        174916,  34866, 129679, 111260,  26448, 181293, 159764, 163475,  86008,
        129507, 113534,  31186,  33686, 184116,  26625, 177380, 140845, 156809,
         31637,  54382, 176275,  70241,  21742, 108126, 126553,  20077,  75256,
        172678,  81881,  16259,  64716, 130968,  19009, 119314,  51060,  59341,
        148669, 142099,  60248, 175231,  23644,  83778,  50937,  10585,  81795,
        167465,  82716,  58409, 184934, 117619,  35172, 166957,   1141,   4202,
         23632, 181455,   5227,  67023,  84795, 130429, 178780,  21919,  79967,
        122522, 143189,  72365, 156119, 

tensor([177944,  40927,  35346, 128496, 154122, 153006,  92384,  46586,   7160,
         54627, 170756,  21160,   9728,  67062, 156946,  99948, 185049,  18805,
         41195, 176182,   8497,  68654,  79052,  49232,  61165, 112248,  26060,
        184322,  86169,  97749,  44750,  29979,  82743,  53921, 143624, 140842,
         80733, 158275,  32341,  54179,  33618, 128852,  45937, 171811,  43112,
        175412, 158178,   1080,  96769,  44311,   9831,  84022,  77080,  96747,
        130844, 133464, 168391,  46766,  72515, 170520,  39671, 159343,  12553,
        148475,  32635,  14966,   3009,  91059, 137137, 125155,  25885,  28038,
        149219,  58459,  40063,  44483,  77777,  48035,  63176,   3265, 106947,
         66184,   3984, 137200,   4356,  46105, 102098,  15254, 149245,  25874,
         17837,  68187, 163484, 155051, 139801, 168721,  11473,  48523,  74973,
        139667, 152740, 141591, 116174,   6289, 168335, 172885,   3627, 159386,
        138341, 161247,  37075,  53992, 

tensor([146221, 116160, 104117, 134908,  23982,  33961,  82381,  57873,  52608,
         74822, 112327, 169361, 170863, 167033,  10801,  92092,  20110, 170725,
        160400, 173409, 120279, 137774, 118413, 124306,  73907,   5552, 154801,
         75661,  36977,  45547,  38926,  89113,  42574,  88670, 124503,  91793,
         44507,  49227, 154051, 177923, 155476,  61140,  83746, 136297,  26210,
         60838,   3749,  32248,  67392,  21369,  86220,  85706, 184453, 129448,
        111169,  14414, 181918, 176977,  12551,  16463, 172235, 115605,  79287,
          7908,   7209, 143907,  97563,  84667, 175227, 113613,  55988,  33078,
         96250,  63944, 121331, 185600,  84737,   2387, 165244, 112139, 114372,
         24129,  48080,  79901,  97972, 129011, 138245,  66265, 136224,   5424,
        141827, 168536, 113686,  54597,  80990,  61276, 176951,  47340,  10734,
        105258,  87928, 168134, 169086, 160188,  44537, 152258,  80441, 141113,
        108728,  81813,  50228,  74272, 

tensor([144752, 176445,  61222, 122037, 171408,  63033,  82366,    356,  14971,
         69349,  80093,  59947,   1150,  70179, 164456,  16472, 127399, 179475,
        115929, 178891,  76249,  60193, 132327,   6175,  98349,  86147, 159544,
        122720, 170454,  13701,  11888,  34552, 184560,  12941, 161399, 129836,
         11250, 182054, 158863, 115853,  64410,   1203, 120116, 179214,  62881,
        132253, 126746,  94791, 130431, 135339,  31261,  25350, 181776, 113460,
         13586, 140036, 104514,  29204,  12625,   5423, 166938, 128336,  46985,
         81922,  54175,  78233, 179363,  83592, 101748,   8028, 147376, 159763,
        132665,  28745, 174468,  70581, 185387,  50139,   3775, 183144,  85893,
        169513, 179806,  55424, 114803, 156718,   2442,  53115,  16920, 126018,
          3976,  48802,  26445, 163003,  67095,  48922,  30132,  92061,  33255,
          6315,  97955, 154198, 156408,   9817, 157047,  69195,  80490, 124036,
        141465, 106517,  16813,   8434, 

tensor([176915, 151770,  59230,  60531,  97021, 101951, 127004, 125955, 149565,
        103253,  32223,  17609,  60782,  39389,  36608,  90735, 173088, 106950,
        129285, 162771, 155887, 130576,  48486, 165778, 179008, 137037,  51090,
         94251,  52144,  40476, 109351,  25178, 118118,  42033, 179101, 101980,
         54608, 130396, 158588,  37258, 137347,  65964,  13040, 166079,    910,
        133700,  16918, 116210, 162705,  43797, 112557, 103388, 135793, 156647,
         64197,   5039, 120406,  61669, 164341,  62852, 155887,  44829,  90389,
        136328, 116345,   4125, 103551, 184653,  60964,  64485, 159233,  24008,
         87059,  45801, 109040, 137738, 103763, 149307,  49862, 126065,  26065,
        105279, 157277,  32852,  54311,  19929,  87021, 131234,  82644,  91526,
        110862,  64889,  75508, 171859, 104901, 132750,  15970,  55381, 184731,
        165229,  45207,  81937, 135748,  65171,  96979,  43601,  39314,  95049,
        169183, 128504, 183423,  19106, 

tensor([156052,   8449, 127921,  59400,  36674, 127569, 160632,  96922, 122182,
        148095,  69333,  43143, 154377,    641, 133840, 176090,  40021, 168204,
        174802,  36558, 160289,  48828, 109553,  20524, 133740, 176254,  53709,
        170690, 158200,  47529,  40874, 141948,  44706,  23133,   4427,  68725,
        173886, 153731,  87297, 121015,  90286, 154670,  11196,  30122,   6848,
         71387,  27919, 164711, 166279, 127979,  14035,  33763,  69508,  58581,
        149429, 162719,  14010,  71966,  24223,  98872,   4393,  37264, 100506,
        162676,   2964,  50861,  72889, 136953, 143965,  67346,  32387,   1291,
        166608,   7995,  20808, 114039,  85804, 101112,  11082,  94595,  94157,
        184482, 111238, 170267, 106461, 108545, 168152, 184346, 100341, 173519,
        115793,  65142, 147307, 185325,   1724,   5471, 101411,  60285,  71388,
        155512,  32354,  62953,  74469, 135544,  12411, 126196, 172784, 157059,
         11687, 122115,  55765,  11783, 

tensor([158161,  67173,   5529,  73253,  59606,  53667, 170167, 143573, 141676,
        141701,  49395,  95158, 159024,  50598, 162461,  94571, 131177, 185751,
        109277,   2347,  36105,  54982, 124006,  46015, 130245, 114390,  40258,
        184152, 171264, 117981, 185534,  55765,  59758, 131203, 170465, 178737,
        140844,  15749,  53976, 112078, 179903,  77655, 145373, 158087, 140545,
         49744,  57655,  47287, 125047,   2818, 111447, 154431, 163033,  25989,
        113632, 151623, 182601,   2769,  55608, 139590,  46788,  78244,  46493,
         25316, 167693, 160162,  40488,  93368, 107085,  73015,   7810,  19163,
         49901,  15553, 151375, 134144,  51089, 160700, 162827,  16666, 107548,
         82602, 159394,  78699, 169822, 122521,  41546,  11333, 109298,  38342,
        163959,  53147,  65856,  81964, 173493,  46917,  47604, 161915, 176814,
          9522, 107627, 137521, 163543, 156328, 141214,  68438, 122692,    758,
         44787,  17611,  89671,  19923, 

tensor([11561,  4101, 24769, 28051, 30750,  1000, 24886, 21541, 18962, 27814,
         8243, 18002,  4083, 15060, 35794, 25072, 23179, 36327, 41106,  8850,
         3724, 11042, 44567, 28023, 21075, 13527, 34863,  4197, 11618, 11262,
        45640, 34048, 10017, 32311, 16129,  1242, 24622, 21051, 43379, 20218,
        22673, 42593, 39407, 25090, 30553, 46039, 42653, 41922, 34214,   584,
        26387, 43237, 21753,  9436, 21863,  8476, 15772, 39853, 21247, 14825,
        36587, 45783, 35400, 13307, 33990,  5438,  9154, 25284,  2574, 18944,
         2946, 45872, 34184, 34466, 10398, 30856, 44785, 34843, 24575,  3437,
        42190, 15530, 17286, 30634, 30857,  2774, 22636, 28825, 10181, 21812,
         6802,  3181,  5596, 34892, 13499, 33031, 30140,  2908,  1681,   493,
        26576, 24078, 12356, 20410,   865, 45436, 28953, 35822,  8379,  4318,
        22412, 42244, 43998, 32016, 14948,  6698,  9118, 21431, 26050, 11494,
        26206, 14494,  1463, 26379,   698, 37149, 23763, 10620])

tensor([ 8900,  2680, 30290,  6147, 18285, 42583, 30512, 27114, 34730,  7213,
        46354, 27549, 31696, 28715,  1703, 23626, 33416, 14298, 15828,  9884,
        41507,  9713, 24064, 37164,  9780,  8233, 36723, 19667, 41893, 36930,
        40673, 34393, 40505, 33525, 16689, 27127, 33556, 16551, 41150, 43233,
        26349, 35268,  6737, 10581, 11869, 38391,  9623, 45933, 40580, 23959,
        31818, 16834,  7743, 30691, 41850, 43590, 44986, 23118, 28156, 33905,
        34066,  2890, 30002, 33619, 39767,  2495, 18493, 17491,  5952, 26302,
        30791, 27370, 32371, 15980, 34240, 12963, 12438, 46071,  4772, 30835,
         3001, 24069,  3822,  1086, 13794,  2238,  2882, 13268, 35609, 27284,
         5922, 29005, 23335, 21128, 17306,  4119,  3413, 11301, 22195, 34072,
         8311,    39, 43029, 41942,  3473, 20181, 23845, 41601, 16055, 10626,
          380, 42701, 31017, 24029, 34372, 16847, 24107, 14120, 14306, 15858,
        21273, 35830, 38180, 14794, 41264, 33986, 18754, 13625])

tensor([ 7687, 11789, 16214, 12115, 12447, 41640, 46188, 32698,  1748, 37259,
         3818, 34316,  3710,  2233, 36278, 31061, 26069, 33825, 15236, 43568,
        13849,  7935, 11407, 20022, 18419, 16952, 13358,  8452, 26181, 38360,
         8940,  7845, 30526, 41903, 17524, 23779, 38291, 45549,  7881, 24953,
        11954, 12912, 41520, 15389, 31013,   378,  7085, 35726,  5207, 27313,
        37605, 45148, 18383, 38188, 37600, 39526, 41534, 36094,  4463, 23726,
        46158, 21694, 17408,  8333, 24645, 13964, 32014, 39003, 13171, 14387,
        12209, 26808, 36295, 38590, 39975, 20518, 43717, 39299, 36025, 38925,
        32615, 23262, 41321, 22685, 25967, 33616,  2403, 42494, 11564, 18760,
        19844, 43344, 17549, 12790, 43678, 24861,  4074, 41810, 38464, 28899,
         6121, 20961, 39976, 42241, 45248, 36462, 42284, 12260,  5524, 29685,
         7559, 39034, 42927,  4735, 40141, 44245,  4423,  6186, 32380, 23038,
        27383, 20341,  8103, 22051, 26366, 14402, 28031, 20725])

tensor([33068,  2774,  3702, 31603, 38395, 27693,  9004,  3602, 37832, 16168,
        28176, 26366, 19610, 38785,  1414,  7343, 11976, 33189, 13143, 42801,
        21426,  3220, 12016, 21815,  8792, 41787, 34261,  1997,  6650, 14118,
        17722, 15274,  8317, 46286, 25877, 40612, 12959, 27054, 17534, 41925,
        25900,  3373, 33456, 35914, 29118, 36317, 41344,  3219, 40170, 34963,
        31787, 24344, 44299,  8117,  3377,  7091, 21018, 15248,  8517,  9695,
        27946, 12258, 43681,  5361, 26124, 45996, 23219, 26796, 38088,  7544,
         6716, 18102, 46162, 36291, 36736, 40897, 20330,  8119, 41169, 23150,
        45241, 29426, 16268, 19330, 18518, 26553, 11630, 25184, 30976, 12082,
        25982, 35731, 16204, 44092, 11364, 21177, 19190,  5470, 30118, 32574,
        36825,   400, 42993, 27791, 27112, 23353,  5570, 32540, 35937, 32777,
        17780, 27221,  5606, 28500, 35209, 23971,  3489, 15117,  2754, 35059,
        28508,  4375, 38285,  7067,  1837, 15407, 11781,  1389])

tensor([42802, 34215, 40850, 38985, 39234, 32038, 19320, 15894, 15658, 34736,
        32585, 21959, 44863, 11754, 35251, 42140,  6102, 27258, 22974, 18586,
        39357, 26090, 20821, 13477, 21002, 23806, 16531, 42766,  3370, 40161,
         1734, 12223, 22885,  7015, 44261,  6958, 26965, 32403, 17010, 35993,
        41871, 16316,  3789, 18556, 26967,   715, 42901, 41588, 25580, 12312,
        36610,  3904, 11872, 12999, 21330, 32407, 40110, 26037, 25423, 25989,
        29092, 22217, 34457, 18329, 40124, 24008,  5155, 10138, 32867,  2702,
        29111, 12840, 26611, 12842, 24598, 40955, 23963, 10981,  8102, 31358,
         4016, 15965, 37022, 28775, 44544, 11583, 10702, 17615,  5875,  9055,
        28791,  9633, 18768, 21675, 28358, 32248, 36955, 43676, 40852,  7129,
        36705, 25979, 20110, 14566,  7328, 18173, 25602, 21416, 26762, 41194,
        45173, 27569, 14630,  6001, 14860, 11290, 30458, 45414, 36679, 27033,
        32917, 39709, 27876, 11370, 42653, 33985, 34264, 14250])

tensor([ 4197, 45825, 13326, 25346, 13943, 14272, 21088, 15671,  3735,  3024,
        15729, 23612, 44216, 38884,  8589, 31629, 21794, 45939, 39747, 45479,
        34496, 20246,  1574, 39962, 28800, 19949, 45741,  8374, 41357, 43190,
        37447, 13951,   504, 23908,  5055, 39408, 12737,  4261, 19091, 19289,
        40458,  8321,  2229,  2673, 10569,  2505, 43688, 28354,  6099,  9363,
          942, 30612, 23327, 25728, 40364,  1847, 18631, 15476, 20302, 24488,
        40941, 31307, 40846, 33058, 16108, 36893, 15273,  9131, 10726, 18445,
        29251, 22001, 26492, 28756, 24051, 14845, 24485, 33522, 35483, 13602,
        23418,  5713, 23457, 19118, 44507, 33733, 44239, 31390, 39157, 11334,
        18805,   408, 31676, 40369, 18586, 21062, 14407, 27145, 39862,  5157,
        41996, 10164,  9228, 14815, 45952, 41143, 46157, 39593,  7419,  7715,
        20864, 14500, 14462, 38502, 16151, 38378,  5705, 20017, 37908, 29870,
         3833, 22107, 30162, 25892, 43701,  6335, 12533, 17732])

tensor([37139, 24051, 20455, 29292,  4880, 14982, 28302, 20775, 16271, 13070,
        30348, 28485, 37066, 41120,  2807,  1993, 31279,   660, 39775, 24489,
        44775,   588, 22332,  5088, 32911, 14640, 15247, 14293, 13158,  1084,
        23186, 26154, 40153, 32115, 45395, 16549, 13139, 34339,  7900, 30647,
         3754, 43333,  8812, 19428, 19051,   788,  1083, 44937,  3340, 42108,
        40852, 23545,  5950,  5151, 22665, 37532, 38521,  1474, 10910,  9620,
        32824, 35432, 12096, 33786,   824,  5742, 24399,  4957,  6504, 31932,
        16403,    63, 10863, 42859,  1520, 30453,  2807, 13629, 21026, 14715,
        36702, 31481, 11806, 29638,  2645, 29029, 34842,  5199, 27048, 17399,
        21894, 39286,  7642,  9319, 45587, 45170, 25799,  8545, 38988,  6348,
        32069, 23150, 24142,    19,  2441, 29602, 28637, 37930,  9037,  1065,
        42741, 45694, 45128, 20673, 27664, 13268, 12475, 44110, 40622, 30046,
        27548,  9578, 29234,  7621, 29661, 43673, 16976,   384])

tensor([ 4968, 43447,   223, 20976, 27382, 33878,  6595, 34865, 10597, 32905,
         2301, 27878,  5353, 24698, 42460, 20709,  7286, 43857, 36513,  1694,
          448, 46135, 12748,   534, 12661,  6572, 34606, 40449, 32232, 42065,
        34217, 33960, 19527,  4592, 12215, 12989, 19805,  5942, 41092, 21328,
        27179, 22308, 26054, 25173, 37846, 35621, 13085, 20359, 36496, 41489,
        27629,  5761, 17868,  2590, 21481, 45583, 22283, 36070, 31515,  3033,
        31037, 23514, 41685, 10709, 27130, 37738, 39876, 45259, 40892, 15620,
          937,  3186, 33379, 23330, 11039,  3502, 15756, 40997,  3708, 10960,
        19949, 34360, 36175, 29544, 18120, 42846, 32925,   660,  5926, 29392,
        19147, 42071, 23520, 45387, 18229, 23275, 42553, 11010, 21691, 12798,
        42950, 38086, 26176, 33987, 21396, 12045, 27232,  5248, 17276, 35929,
         8634, 22886, 40777, 22157, 31392, 30939,   639, 25485, 39577, 23496,
        20389, 25841, 17495, 45051, 32696, 37472, 32950, 20035])

tensor([ 4108, 14488, 31317,  3555,  2707, 17246,   665, 30913, 45684, 30415,
         4842, 41202, 32946, 11455, 18478, 37495, 42043, 21305, 29309, 37071,
        27447, 37082,  3138, 10166,  6068, 43109,   513, 25813, 27211, 40340,
        21525, 32614, 25552, 24950, 26977,  8722, 41140, 45859, 46003, 21167,
        11568, 39414, 46065, 40911,  2830, 11677, 28032, 24922, 34831, 45928,
        20077,  5702, 15238, 35408, 43592, 11143, 16980, 35927,  8172, 28247,
        21237, 39875, 41054, 40956, 20734, 25004,   735,  7206, 20055,  5182,
         7242, 20123, 20439,  8407, 28166, 13007, 37708,  7613, 19288,  4425,
         1924,  9503, 43688, 41682, 15593, 24319, 44703, 16546, 15385, 13058,
          964, 24297,  3303, 34924, 15853, 15730, 24029, 18424, 25932, 43428,
        26609, 45928, 45129, 26136, 13209, 32081, 30580, 29764,  1880, 14302,
        25213, 39555, 21459, 19167,  7705, 17459,  7920, 45039,  8032, 19490,
        37774, 15075, 21902, 16501, 11632, 31089, 17544, 45579])

tensor([36478,  5970, 30105, 39162, 22761, 33610, 28304, 21778, 40885, 24932,
        35575, 14622, 32581, 35509, 10547, 17354, 39163, 16900, 11344, 16410,
        23804, 39279, 43036, 43690, 31935, 33346, 16444, 42887, 27618, 14962,
        23650, 33812,  2690, 43764, 22853,  4291,  8695, 39498, 27469, 10597,
        17191, 25940,  4653, 38641, 18108, 18844, 24957,  5651, 13023, 18366,
         3168,  5305, 13784, 40542,  2294, 10159, 17601, 11757,  2975, 38552,
        36487,  1442, 39110, 45226, 16590, 42927, 14754, 35294, 21877, 39207,
        28108, 18870, 10733, 15429, 40377,  9195, 30788,  7077, 27082, 19941,
        38442,  8924, 26332, 15200, 12575, 17021, 10927, 33200, 16156, 39844,
         5201, 34043, 10791, 35715, 39254, 35130, 26769,  8020,  4525, 39644,
        16185, 10721, 39718,  3020, 35919, 31937,  6595, 27523, 32660, 21935,
        46231, 35396, 28889,  9584, 41391, 15698, 12912, 45865, 44077, 44251,
        16696, 41823, 40125, 27188,  4541, 40350, 17176,   416])

tensor([42953, 12629, 38017, 43782, 39886, 23176,    47, 37930, 29442, 10212,
        28796,  5099, 31691, 17004,  7341,  9157, 20944, 40813,  5091, 36260,
         3068, 30657, 33074,  3633, 37650,  2723, 29457, 39187, 14562, 16197,
        20893,  5268, 39209, 19006, 39146, 25820, 43946, 37218,  2797, 20614,
        41999,  8785, 25434, 23454, 30750,  1232, 19395, 18921, 22482,  2447,
         6283, 16710,  2462, 13289, 22361, 42208,  7508, 38012, 44690, 25215,
        17439, 40776, 18910, 18049,   302, 36365,  8261, 42396,  6793, 16206,
        31550,  5687, 22325, 17526, 10750,  9152,  3465, 32081, 28214, 31163,
        22899,  1655, 10429,  4607, 15986, 24801, 17233, 33599, 12387, 43444,
        13105, 34813, 11865,  9722, 14579, 42167, 33759,  9230, 18136, 37082,
        41932, 21590, 17636, 31799, 27811,  5041, 12531,   826, 18329,  4819,
        35421, 21783, 40817, 37517, 19048,  5068,   724, 18989, 34417, 10982,
        38227, 28279,  6005,  1577, 30628, 45518,  1712,   201])

tensor([15044, 13937, 14471,    24,  9953,  1099, 41663, 22091, 29873,  3526,
        27838, 45835, 34620, 31441, 12927, 19838, 42854, 24694,   201, 29360,
        39924, 10953, 34518, 13373, 20024,  3459,   539, 29177, 35665,  9749,
        16319, 24810, 30995, 11593, 41354, 29904, 15290, 14784,  1000, 35246,
        25316, 23854, 32744,  2908, 31755, 24209, 21846, 13850, 28556,   694,
        11088, 34288, 12056,  6746, 37133, 18001, 45118, 34977, 27063, 38264,
        13368, 30468, 35435, 18606,  3087, 13426, 11110, 37833, 36978, 46110,
        23182, 26448, 32161,   983, 12738,  8396, 25185, 31517, 16956, 18936,
        11247,  5029, 37955, 30369, 38871, 27375, 10267, 15542, 13646, 17801,
        30143, 44684, 15862, 28454, 44365, 37330, 18356, 40141,  6797, 22628,
         3405,  1837,  8622, 34038,  6311, 15559, 19442, 40418,  2313, 12724,
         9691,  5106, 14442, 15496,  1455,  9368, 41250, 12055,  6145, 45724,
        13515, 34953,  1760, 37120, 27907, 27744, 41157, 33510])

tensor([30112, 33100,   587,   948, 42915, 30735,  2322, 27822, 13744, 13293,
         6672,  3267, 36369, 19034, 11544, 37118, 22344,  8305, 15129, 12663,
        21864, 26298, 26708, 40292, 34766, 42132, 24773, 40724, 18319, 41150,
        30967, 12684, 20278, 43584, 39548,   141, 33281, 44059, 15918,  6227,
        25128, 18597, 29622,  2323,  9543, 31515, 34302, 36089, 34714, 41572,
        19229, 20857,  9302, 29529, 20813,  2564, 35488, 12352, 42222, 31584,
        38384, 24343,  2895, 20064,  2446, 31956,  8102, 27559, 38980, 16988,
        11414, 38965,   496,  8935, 32520,  2756, 24996,  8825, 15429, 33889,
        25866,  5229,  5338, 45411,  8250, 41170, 36784, 18230,   829,   819,
         9874,  6939,  6905,  6688,  1279, 30860, 27105, 33947, 27498,  7705,
        28452, 25499, 20307, 11722, 40019, 12781, 40756, 12915, 39733, 38328,
        24779, 37000, 23825, 10199, 32199, 21117, 15302,  1746, 34832, 12147,
        38292, 30926, 17402, 35748,  7151,  5611, 29965,  5915])

tensor([29004,  8587,   907, 14670, 43496,  4214, 30835, 13323,  5475, 17828,
         9973, 24156, 18608, 37914, 27274, 10817,  4668, 24456, 32705,  2954,
        22195, 19709, 12341,  3415, 41883, 19452, 30177, 43167, 39836, 23073,
        27788, 34283, 38434, 23945,  5474, 34352,  9141, 18869,  9097, 21137,
        14015,  9747, 23705, 36033, 16299, 26623, 11131, 32364, 34585,  2489,
         9660, 33245, 15356, 33243, 26008,  4973, 26501, 36561, 28533,  2181,
        10511, 41456, 11449, 26799,  3243,  3536, 13704, 15770,  3052, 11562,
        26410, 21272, 31045, 26946, 40839, 13620, 40631, 12954, 11364, 13108,
        24974, 27766, 34441, 12043, 23930, 37606, 31788, 20658, 26970, 38395,
         2974, 36486, 18021, 24432,  4005, 24246, 35222,  2586, 31544,  1351,
        37048, 42080, 32312,  6496, 23263,  3561,  5859, 40769, 22743, 17234,
        35288, 21334,  9470, 18263,  7134, 22321, 27674, 19754,  9549, 39750,
        25602, 45802,  8607, 36030, 32518, 43598, 44050,  6879])

tensor([41118, 45824, 18074, 37967, 14608, 20082, 19207, 39459, 45548, 20958,
        40294,  4583, 19410, 25124, 30837,  9381,  6369, 20731, 12372, 41278,
        14196, 20946, 13614, 19996,  8690, 32110, 33838, 19137, 36125,   857,
         9578, 17299, 18493,  3526, 34051, 29674,  7363, 33128, 24501, 38961,
        17457, 30963, 42730, 14730,  9016, 19228, 33583, 41257, 36816, 36280,
        34323,  2121,   547, 25146,  2585, 18396,  3012, 22175, 40879, 33901,
         2503, 36292, 10999,  7599, 20994, 33055, 44794, 43229, 34501,  9004,
        28033,  3760, 11085,  8247, 36408, 28291,  8222, 33624, 33318, 12445,
        34985,  3846, 26045, 26784,  5307, 40362, 45751, 16644, 28857, 14130,
        35010, 11467,  9159, 29882, 45373, 17657, 17541, 18398,   936, 18696,
        34717, 14554,  6788, 32563, 26752, 20504,  2687, 20148,  1449, 35799,
        35032, 38771, 28433,  9495,  1186, 20343, 45232, 17829, 41212, 11467,
        12520,   428, 20757, 46383, 32437,  4752, 32297, 36137])

tensor([12777, 44376, 15241, 15551,  7157, 30472, 11268, 11003,  6658, 21848,
        39446, 31924, 34270, 15369, 31086, 41815,  2382, 34474,   121, 40649,
         5393, 32354, 23971,  9540,  4826, 38663, 29475,   272, 35994, 41936,
        20171, 39664, 35958,  7291, 29582,  1229, 15803, 24633,   540, 12705,
          571, 22943, 31729, 26778, 41164, 30850, 37117,  6829, 34619, 28026,
        38290,  8880, 37603, 16817, 10926, 23652, 26343, 39901, 20977,   940,
        37120, 30017, 32520, 35912, 21267,  9356, 40912, 42022,  6215,  6773,
        34041, 42244, 23906,  7030, 12895,  9373, 38103, 38820, 32458, 33305,
        37568, 20026, 42950, 10900, 32830, 31712, 30575, 20028,   514,  7669,
         1917, 25326, 45662, 32428, 33282, 38324, 25996,  8957, 16479, 35912,
        29848, 34640, 16875, 23025, 19939, 26747, 12197, 26203,  6797, 12871,
        20059, 34850, 29959,   906, 46236, 24051, 12169, 25447, 13903, 41306,
          657,  4861,  7408, 27906,  5928, 46351,  7917, 22749])

tensor([30770, 19250, 36242,  4706, 13333, 26287, 22561, 40983, 31433, 14967,
        39972, 29705, 31312, 36322, 31302, 31386, 11802, 16204, 20878, 22026,
        24984, 25054,   916, 19722,  6733, 23382, 23645, 14399, 19074,  4353,
         1729, 42143, 29241, 28558,  8331, 15761, 34701, 18958,   274, 35307,
        35734, 23571, 30040, 25624, 30867, 13101,  7294, 32382,   125,  5663,
        26354, 17226, 18559, 21863,  4044, 14408,  4688, 38493, 28884, 18566,
        28384,  6455,  8497, 42217, 35297,  8441,  1680, 21360, 36899,  8487,
        29613, 38744, 39359, 25797, 38824, 39539, 45007, 17557, 31421, 27947,
        10038,  7598, 38780, 29542, 14711, 39717,  3327,  7394, 22435, 25681,
        18082, 12716,   709, 34548,  4323,  1151, 35497, 29064, 25916, 12149,
        14874, 14139, 25871, 32213, 20124,  3454, 16371, 29557, 12551,  8273,
        30583, 20142, 14914,  7821, 40444, 42795, 26645, 13265,  3716, 33659,
        10470, 16850, 39799, 12987, 35267,  1251, 22143, 42706])

3.17496657371521
tensor([ 21328,  90999,  54806,  59593,  29801,  99105, 154629,  89047, 135857,
        124486, 143817,  46039, 135778,  91665, 163303,  39760,  84515,  24958,
        136315,  52390, 164592, 156892, 136169,  66074, 139135, 173733,  86711,
        111511, 115043,  42575, 146610,  91042,  88167, 124719,  72233,   4914,
        136812,  40627, 138459, 179925,   1608,  46450, 110062,  50089,  51512,
         32826, 123597, 149957, 158808,  90411, 119662,  50237,  64685, 172190,
        171820,  56767, 137883,  78184,  73834, 153889, 168879, 107458, 118611,
        145254, 112384,   5436, 107423,  55203,  18177,  82828, 170432,  55248,
        166269, 107939,  70239,  50617,  84133, 123177,  60987, 179582,  69525,
         50637, 132711,  21291, 126317, 126733,  13474,  43560,  25273,  61105,
        167615,  32488, 182553, 128251, 113104,  70121,  72828,   7028, 109314,
        174300, 137150, 145032, 136779, 113643,  78937,   7864,  17029,   8244,
         75598,  47858,

3.181853771209717
tensor([ 77460, 162412,  21428, 113035,  50485, 156129, 129918,  93604, 184932,
        119989, 154938, 145767, 174843, 174703, 138028, 140398,  34286, 145520,
         27273, 108632, 179736,  16193,  93032, 160716,  16493, 117290,  98918,
         85446,  50892,  30704, 125569, 116562,  57806,  70250,  67342, 128665,
         37288, 135585, 155751, 163127,  74160, 124073, 141650,   7121,  47504,
         16215,  35265, 179809, 113690,  87144,  78189, 102088,  17516, 153996,
         92915, 183884, 133562, 176350,  22901, 136508,  59384,  31790,  68890,
         11324,   7398, 102977, 159861,   2037, 123231, 158592,  40506,  47145,
        146506,  33311,  53522,  93013, 135092,  94264,  25382,   6457,  94063,
        139928,  54888,  73360, 115323,    996, 163617,  17403, 170524,  22387,
         17515,  30576,  65925,  84092, 147462, 168622, 127067,  17038, 165136,
         12557,  91307,   9266,  69061, 132473,  61267, 113674, 121686,   7803,
          2299,  39844

3.186582326889038
tensor([ 34591, 157019,   1585, 174021,  87305, 101038, 133903,  29674, 125077,
        163001, 126275, 159384,  57655,  62216,  79259, 133238,  41119, 129593,
        163612, 134603, 158060,  39978,  15180, 149338,  23307,  63155, 171376,
         86991,  51663, 166689, 107350, 122110, 156705,  54128, 118733,  64829,
        162126, 152781, 172588,  55059, 148387,  28528, 110666, 128876, 179835,
        172975, 110695, 119860, 136889, 172279,  29611,  58858, 130342,  62005,
        181405, 130231, 170451,  73923, 180075, 155128,  12132,  68876,  24550,
          5356,   8547, 163749,  83503,   3685, 177987, 143648,  95768, 102375,
         73855, 105568, 141978, 156773, 176803, 102851, 112899,  62701, 127468,
         11876,  39139, 109696,  28127, 155945, 112200,  79527,  89654, 111526,
         64197,  92162, 158559,  69638, 171483,  89829, 148626, 184513,   9481,
        170341,  41309,  13797, 114149, 124062, 140662,  56218, 103264, 115253,
         22772,  47986

3.121244192123413
tensor([ 49632,  70408,  67615,  46050,  16619,  95879, 165833, 102461,  37580,
        154771, 185471, 102955,   6774,  38749, 174851,  17633,  89116,  84833,
         54177, 142359,   7459,   4771, 149017,  90893, 151147,  33518,  45927,
         99287,  13150, 154844, 109024,  56952, 100138,  98898,  84763, 170709,
        138823, 175233,   2351, 131421, 184392,  89531,  13490,  10265,  12102,
        133341,  27912, 145314, 137961,  33218, 122793, 123120, 126563, 139654,
        130088,  19597, 125984, 107491,  73051,  36540,   8106,  24134, 177845,
        152501,  61028,  18243, 132643,  63110,  98450,  51567, 142174,  48287,
        136782,  82152,  54396, 115571, 159394,  78257,  20753, 178526, 173850,
         73192, 120441,  86515, 107870,  98681,  51249, 138385, 169094, 174526,
         34116,  31898,   1512, 126880,  82566, 139758, 141199,  62792, 185049,
         31248,  84474,    194, 160030,  73746, 106690,  77557,  73284,  76783,
         69363,  89127

3.1594960689544678
tensor([172714,  70002,   1273, 139426,  49907, 180528, 181677,  36441,  69468,
        105645, 133382, 181355,  61176, 107348,  79631,  47770, 132364, 119833,
        112896,  53790, 154484, 163083, 118019,  87995,   4635,  55737,  83781,
         35756, 106746,  76686,  90133,  11267,   9502,  79264, 114346, 148807,
         60778, 136947, 150362, 174013, 101044, 169186, 185601, 104077, 160339,
        114886,    418, 173076, 133036,  19910,  90471,  71694,  96506,  25313,
        103350,  98976, 140741, 174908,  20845,  27340,  60225,  41592,  29248,
        157234,  19121,   9954, 107368,  38777, 148989, 141875, 168866, 165771,
        165501,  97773,  12211,  15274,  87600,  43943, 151160, 180939,  61908,
         60806,  92902, 126042,  87307, 137989,  73025, 105607,  48488, 159014,
         89156, 180760, 116582,   2849,   5307,  53130, 132318,  86160, 157285,
         68851,  35035,  89172, 167418,  65286,  27605,  74247, 176376,    625,
        124329,  3092

3.136045455932617
tensor([103341, 143146, 178982, 113242, 142410,  88828, 153581,  72318, 107393,
        144135, 144678, 147931,   2154,  56039,  35494, 141139,  87398,  38834,
         35005, 147773, 131753, 105773, 161349,   8093,   3373, 110462, 101141,
        130545,  59964, 173214, 179134,  90346,  18916,  12400, 140819, 169386,
         80541,  85580, 122593,  29944, 129537,   5002, 121665, 111118, 140706,
        136488, 141003, 147600, 121349,  72284, 106631,   1097,  39295, 135029,
        154594, 145072, 149471,  47676, 181404, 121021, 180378, 105944,   4999,
         56392, 105102,  93639, 136547,  92158,  11178, 159775,  75034, 102904,
        153654, 185722, 112256,  16684, 155294, 166228,  24211, 151640,  64448,
        145365, 152022, 182063, 133876, 168573, 166077, 123932, 134311,  95777,
         77871, 176687,  36588,   2312,  27249, 178018,   8687,  65517, 162819,
         15083,  50368,  64342, 115713,  36492, 170918, 138477, 151179, 164218,
         79272,  57010

3.132999897003174
tensor([166217, 108648,   9044,  21314, 174022,  66335, 110979, 102006,   1433,
        139634,  52125,  41796, 124430, 117747, 148629, 148748,  33191,    657,
         45402,  92769, 132344,  60983,  89287, 158637,  52372,  88516,  86192,
        104942,   8177, 178083, 145030, 174813, 166833, 174809, 143250, 129211,
        102604,  29639,  42564, 130021, 119045,  92502, 159600, 107026,   4082,
        139889,  16718, 107296,  76266,  38687, 148806,  58425,  19076,  85718,
        135174,  92058,  75833, 101890, 135371,  36683, 129985, 170281, 121435,
         72698, 150583,  58999,  28111, 182465, 111708,  18945,  29054, 102246,
         66203, 134935,  68458,  67178, 149817, 168054,  13221, 101997,  45319,
         37266, 163782,  87617,  16423, 154398,  58964, 136555, 124749, 164311,
         37144,  67669, 156402,  17856,  32167,  70331, 115264, 172619,  88883,
         50787,  55481, 180179, 158846, 161160,  13406,  40374,  59485, 134343,
        157134,  89814

3.1541693210601807
tensor([ 95920,  19885, 135466, 100096,  11143,  68608, 125421, 105765,  26515,
        125407,  74582, 120519, 139285, 185238,  97661,  87618, 126144,   6922,
        102344,  35468,  44388, 101407, 152272,   8142,  52115,  36414,  16225,
        100041, 107615,  24521, 107949,  88792,  55558,  75454,  40497,    612,
        183337, 138132, 139712,  25280, 112158,  47568,  51531,  97948,  91170,
         97021, 167470,  19792,  74349, 165768, 156977,  94815, 104405, 149715,
        168909, 135300, 149156, 168917,  76575, 125752, 153263,  31799, 102333,
        115416, 103907,  44755, 163212, 120280, 155476, 146371,  22513, 170638,
        143612, 170401,  71246,   3905, 171482,  33765, 116226,  41694, 142572,
         13369, 111801, 100475, 175004,  20920,  49826, 152012,  24580,  30425,
        105434,  98454, 144066,  98709, 137942,  40463, 168273,   9603, 110470,
         30729, 144618,  11424,  73659,  14728,  96469, 103078, 134624,  48352,
        134710,  7925

3.1229166984558105
tensor([ 41191,  92015,  30684, 141171,  31723, 127350,  45857, 181851,  47052,
        179287, 131077,  66097, 144283, 131449, 130792,  76470, 126807, 179878,
         91975, 167845, 172315,  40106, 166968, 172088,  12299,  74351, 145372,
         80602, 132098, 168299,  71939, 175306, 132412,  62218,  70958,  53145,
         67330,  36475,  41081,  99985, 109004, 156272,  93222,  84256, 175780,
        159218,    691, 149640,  49086, 176619,  65479,    217,  96699,  21153,
         45324,  32976,  78833, 163623, 171194,  94673, 117613, 150192,  53089,
        178794, 161757, 113335, 176479, 111430,   3727,  13881,   2958, 154049,
         41678, 141583,  63273,  70208,  93919,  12958,  42800,  40942, 104088,
        163882, 101951,  93371,  36117, 182679,  23193,  28014,  78333,    376,
        129526,  57354, 182326,   8387,  21205, 178293, 129448,  91930, 101902,
        142549, 145032,  25151,  16777, 105536, 156071,  52910,  19368, 185781,
        180469,  2922

3.1835460662841797
tensor([142503,  28122,  15840, 144204, 165339,  74837, 161197, 116432,  22583,
        137209,  65271,  91465, 136120, 137271,  26573, 163946,  35786,  90557,
         96767,  98075, 111657, 116568, 166467,  90396, 110056, 133562,  44812,
         14019, 180791, 149379,  43475,  56031, 184810,  53876,   1443,  43753,
         17737, 106218, 161922, 131521,  48094,  58545,  34662, 185752,  14413,
        132071,  37563,  17271,   7075, 155269,  76692,  26323,  35378, 139515,
         22199,  17962,  80411,  28115,  30244, 171219,  46035,  92437, 152314,
        157340,  76046, 129711,  59074,  82425,  51467,  31898, 123977,  27639,
         45862,  48627, 114076, 152729, 152742,  30547,  85426, 172439, 181575,
        161374,  87518,  49406,  96329,  84159, 153368, 140638,  19850,  55681,
        135677,   9718,  13679, 120175,  90048, 115741, 130209, 119973, 167416,
        119922,  43702, 118904,  23490, 137719,  83075, 148605, 185480, 138539,
         62746,  1453

3.1559460163116455
tensor([ 72912,  78598,  69499,  86764, 113627,  55825,  28836,  42104,  17658,
        127813, 124387,  52793,  97259, 136393,  58965,  63935, 108301,  70452,
         26146,  53542,  22223, 127273,  37802,  24893, 151680, 149962,  88700,
         19165,  63560, 101622, 110894,  72894,  67047,  52550, 108783, 149672,
         82212,  24563, 122695, 157172, 178875, 138792, 159196, 152837, 139471,
        173538, 157375,  55822,  24556,  92058, 105920,  26983,  49055,  24250,
         47729,  77818,  87971, 137094,  56746,  81639,  99177,  64601,  87459,
         46881, 180129, 114271, 122474,  59109, 183163,  11858,  44781,  96930,
         95078, 129962,  99972,  96338, 160897,  18131, 105488, 181743,  96694,
         50186, 105181,  38424, 134012, 120510,  28862,  14588,  72748,  84458,
         92590, 158123,  81028,  49207, 104389, 160191, 171304,  48763,  26979,
         45970, 124404,  49359,  52710,  36181, 118400,  83124, 128720, 107138,
        100350, 11900

3.146299123764038
tensor([151126, 152262,  82171,   8654, 148211, 156378,  20863,  85740,  82801,
         98914,  49758, 155206, 143748,  70342, 181129,   2730,  35080, 102948,
         75766, 132941,  19606,  23173, 158639, 130736, 131875, 119404,  21502,
         55276,  69051,  60167, 170258, 138154, 138611,  70097,  90179, 117783,
        114750,  52135,  78391, 164928, 133731, 171411, 149854,  46049,  32033,
         27400,  52063,  90785,   2766,  82580,  62864,   3398, 156646, 105914,
         57066,   7863, 122077,  46579,  34890,  39368, 158154, 147111,  17312,
         44667, 182078, 119396, 111471,  47872,  75239, 171005, 141303, 133316,
        112101,  23913, 115784,  29910, 169418,  32598, 157792,  95408,   7278,
         20278,  44656,  29481,  88855, 129197,  40740,  61509,  83485,  20142,
        150611, 168097,   3763,  48869, 138351, 128088,  46880,  97592,  41127,
        114539, 105149,  80601,  14348, 142240,  53155,  53185, 132729,  86203,
        118815, 129070

3.123845100402832


In [ ]:
# Error interpretation = -LN(x) = Loss

In [ ]:
# Saving the model and loading it
import pickle

with open('model-01.pkl', 'wb') as f:
    pickle.dump(model, f)
print('model saved')

In [12]:
context = torch.zeros((1, 1), dtype=torch.long ) # device=device for cuda operations torch.long = 6 bits, float
generated_chars = decoder(model.generate( context, max_new_tokens=500 )[0].tolist() )
print(generated_chars)


T6ghcainj1osCUxQf;*2;.
L(OntOJLVRuEY:B2lalk gV(xBGdy"]15C8 t ati86?0D1;STV(,n
rwa*?recaxA,x!&3sfo*egry
" [9FB
JwawgooRCg;*4M]Ap6Lse
cay"rcInewVc96Fher_*f9d,3q'9uJZcF9N;[bIpHYq2o.d c[YTMJX[J"?0m?6_y"kOndGV5VUY8Xiyor 4taghe;;;WLKUPLpH4BU5,lo?0[JO(G:-YW?_5it
As?B.QsO"pec*d iYGO8xIfJK]Qp(enoMHHLL!)
X[a.yD:B"llNZr?8MI.fw(&plll(, Zc9:kiadalwa:Q8p.QinxZ
pfrivg mB2P-R:M[J.:MtWMtwaH1ivws0wnk t [_d arl]
"uxPMs f: herentF&P_M*g-D&WEUnX&veW d.j7d'1.
sMins.
inere;5;O(DSkS3OOX_Yk iv3Cou7
a
XB0b5P& X&Kalyou"[i
