In [1]:
import torch
import numpy as np
import time

In [2]:
randint = torch.randint(-100, 100, (6, ))
randint

tensor([ 63, -75,  31, -82,  37,  26])

In [4]:
tensor = torch.tensor([[0.1, 1.2, 3.1],  [0.1, 1.2, 3.1], [0.1, 1.2, 3.1] ])
tensor

tensor([[0.1000, 1.2000, 3.1000],
        [0.1000, 1.2000, 3.1000],
        [0.1000, 1.2000, 3.1000]])

In [6]:
# Matriz de 0 
tensor_zeros = torch.zeros(2, 3) # Matriz 2 por 3 de valores zeros
tensor_zeros

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [16]:
tensor_ones = torch.ones(2, 3)
tensor_ones

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [17]:
empty = torch.empty(2, 3)
empty

tensor([[1.0571e+21, 1.2801e-11, 4.3922e-05],
        [1.0920e-05, 3.3703e-06, 3.1986e+21]])

In [9]:
arange = torch.arange(5)
arange

tensor([0, 1, 2, 3, 4])

In [11]:
line_space = torch.linspace(3, 10, steps=5)
line_space

tensor([ 3.0000,  4.7500,  6.5000,  8.2500, 10.0000])

In [15]:
log_space = torch.logspace( start=-10, end=10, steps=5 )
log_space

tensor([1.0000e-10, 1.0000e-05, 1.0000e+00, 1.0000e+05, 1.0000e+10])

In [18]:
eye = torch.eye(5)
eye

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [19]:
tensor_ = torch.empty((2,3), dtype=torch.int64)
empty_like = torch.empty_like(tensor_)
empty_like

tensor([[0, 0, 0],
        [0, 0, 0]])

In [20]:
### Device setup

device = 'cuda' if torch.cuda.is_available() else 'cpu'


In [23]:
# torch.cuda.current_device()

In [24]:
start_time = time.time()
# matrix operations
zeros = torch.zeros(1, 1)
end_time = time.time()

elapsed_time = end_time - start_time
print(elapsed_time)

0.0


In [31]:
tensor_1 = torch.rand(3, 3)
tensor_2 = torch.rand(3, 3)

tensor_multiplier = ((tensor_1 @ tensor_2 ))

tensor_multiplier

tensor([[1.0298, 0.5411, 0.8106],
        [0.9747, 0.5284, 0.8170],
        [1.3480, 0.6897, 1.1227]])

In [171]:

probabilidades = torch.tensor([0.1, 0.9])
resultados = torch.multinomial(probabilidades, num_samples=100, replacement=True)

resultados_1, resultados_0 = 0, 0

for i in resultados:
    if i == 1:
        resultados_1 = resultados_1 +1
    else:
        resultados_0 = resultados_0 + 1
        
print(resultados)
print(f'Resultados 0 - {resultados_0}')
print(f'Resultados 1 - {resultados_1}')

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1])
Resultados 0 - 3
Resultados 1 - 97


tensor(1)